export const BASE_BRIDGE_CONTRACT = '0xa4fac7a16d43f53adf0870001ccec603155eacdd';
export const DEFAULT_BRIDGE_CONTRACT = '0x8c6cEf00ec5bB62Be675E472BA900BE24A2D32e8';
export const BRIDGE_OUT_ADDRESS = '0x8c6cEf00ec5bB62Be675E472BA900BE24A2D32e8';
export const BRIDGE_CONTRACT_ADDRESS = BASE_BRIDGE_CONTRACT;

export interface ChainConfig {
  id: number;
  name: string;
  symbol: string;
  rpcUrl: string;
  explorerUrl: string;
  hexChainId: string;
  logoColor: string;
  type: 'evm' | 'solana';
  bridgeContract: string;
}

export const SUPPORTED_CHAINS: ChainConfig[] = [
  {
    id: 8453,
    name: 'Base',
    symbol: 'ETH',
    rpcUrl: 'https://mainnet.base.org',
    explorerUrl: 'https://basescan.org',
    hexChainId: '0x2105',
    logoColor: '#0052FF',
    type: 'evm',
    bridgeContract: BASE_BRIDGE_CONTRACT,
  },
  {
    id: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    rpcUrl: 'https://eth.llamarpc.com',
    explorerUrl: 'https://etherscan.io',
    hexChainId: '0x1',
    logoColor: '#627EEA',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 42161,
    name: 'Arbitrum',
    symbol: 'ETH',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    hexChainId: '0xa4b1',
    logoColor: '#28A0F0',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 10,
    name: 'Optimism',
    symbol: 'ETH',
    rpcUrl: 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io',
    hexChainId: '0xa',
    logoColor: '#FF0420',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 137,
    name: 'Polygon',
    symbol: 'MATIC',
    rpcUrl: 'https://polygon-rpc.com',
    explorerUrl: 'https://polygonscan.com',
    hexChainId: '0x89',
    logoColor: '#8247E5',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 56,
    name: 'BNB Chain',
    symbol: 'BNB',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    explorerUrl: 'https://bscscan.com',
    hexChainId: '0x38',
    logoColor: '#F0B90B',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 43114,
    name: 'Avalanche',
    symbol: 'AVAX',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    hexChainId: '0xa86a',
    logoColor: '#E84142',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 250,
    name: 'Fantom',
    symbol: 'FTM',
    rpcUrl: 'https://rpc.ftm.tools',
    explorerUrl: 'https://ftmscan.com',
    hexChainId: '0xfa',
    logoColor: '#1969FF',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 25,
    name: 'Cronos',
    symbol: 'CRO',
    rpcUrl: 'https://evm.cronos.org',
    explorerUrl: 'https://cronoscan.com',
    hexChainId: '0x19',
    logoColor: '#002D74',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 324,
    name: 'zkSync Era',
    symbol: 'ETH',
    rpcUrl: 'https://mainnet.era.zksync.io',
    explorerUrl: 'https://explorer.zksync.io',
    hexChainId: '0x144',
    logoColor: '#8C8DFC',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 59144,
    name: 'Linea',
    symbol: 'ETH',
    rpcUrl: 'https://rpc.linea.build',
    explorerUrl: 'https://lineascan.build',
    hexChainId: '0xe708',
    logoColor: '#121212',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 534352,
    name: 'Scroll',
    symbol: 'ETH',
    rpcUrl: 'https://rpc.scroll.io',
    explorerUrl: 'https://scrollscan.com',
    hexChainId: '0x82750',
    logoColor: '#FFEEDA',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 81457,
    name: 'Blast',
    symbol: 'ETH',
    rpcUrl: 'https://rpc.blast.io',
    explorerUrl: 'https://blastscan.io',
    hexChainId: '0x13e31',
    logoColor: '#FCFC03',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 5000,
    name: 'Mantle',
    symbol: 'MNT',
    rpcUrl: 'https://rpc.mantle.xyz',
    explorerUrl: 'https://explorer.mantle.xyz',
    hexChainId: '0x1388',
    logoColor: '#000000',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 100,
    name: 'Gnosis',
    symbol: 'xDAI',
    rpcUrl: 'https://rpc.gnosischain.com',
    explorerUrl: 'https://gnosisscan.io',
    hexChainId: '0x64',
    logoColor: '#04795B',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 1101,
    name: 'Polygon zkEVM',
    symbol: 'ETH',
    rpcUrl: 'https://zkevm-rpc.com',
    explorerUrl: 'https://zkevm.polygonscan.com',
    hexChainId: '0x44d',
    logoColor: '#8247E5',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 7777777,
    name: 'Zora',
    symbol: 'ETH',
    rpcUrl: 'https://rpc.zora.energy',
    explorerUrl: 'https://explorer.zora.energy',
    hexChainId: '0x76adf1',
    logoColor: '#000000',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 34443,
    name: 'Mode',
    symbol: 'ETH',
    rpcUrl: 'https://mainnet.mode.network',
    explorerUrl: 'https://explorer.mode.network',
    hexChainId: '0x868b',
    logoColor: '#DFFE00',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 169,
    name: 'Manta Pacific',
    symbol: 'ETH',
    rpcUrl: 'https://pacific-rpc.manta.network/http',
    explorerUrl: 'https://pacific-explorer.manta.network',
    hexChainId: '0xa9',
    logoColor: '#000000',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: 999,
    name: 'HyperEVM',
    symbol: 'HYPE',
    rpcUrl: 'https://rpc.hyperliquid.xyz/evm',
    explorerUrl: 'https://purrsec.com',
    hexChainId: '0x3e7',
    logoColor: '#00FF00',
    type: 'evm',
    bridgeContract: DEFAULT_BRIDGE_CONTRACT,
  },
  {
    id: -1,
    name: 'Solana',
    symbol: 'SOL',
    rpcUrl: 'https://api.mainnet-beta.solana.com',
    explorerUrl: 'https://solscan.io',
    hexChainId: '',
    logoColor: '#14F195',
    type: 'solana',
    bridgeContract: '6insNE7EpnkQmfpjqR96WZ7EtVo8Q8c4JsUdFZTWjmR1',
  },
];

export const MEGAETH_CONFIG: ChainConfig = {
  id: 6342,
  name: 'MegaETH',
  symbol: 'ETH',
  rpcUrl: 'https://rpc.megaeth.com',
  explorerUrl: 'https://megaexplorer.xyz',
  hexChainId: '0x18c6',
  logoColor: '#00FF6A',
  type: 'evm',
  bridgeContract: DEFAULT_BRIDGE_CONTRACT,
};

export const BRIDGE_CONTRACT_ABI = [
  {
    inputs: [],
    name: 'deposit',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getBalance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nonce',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
      { indexed: false, name: 'destinationChainId', type: 'uint256' },
      { indexed: false, name: 'nonce', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
    name: 'DepositRequested',
    type: 'event',
  },
] as const;

export const BASE_CHAIN_ID = 8453;
export const MEGAETH_CHAIN_ID = 4326;

export const MIN_DEPOSIT = '0';
export const MAX_DEPOSIT = '100';
